name: Check Minimum Score

on :
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'data/**'
      - 'requirements.txt'
      - 'README.md'

permissions:
  contents: read

jobs:
  build_docker_image_and_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: https://index.docker.io/v1/  # Dockerhub registry
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile  # Path to Dockerfile
          push: true
          tags: padamsingh2024/da-201o:both_fail  # image name

  pull_docker_image_and_evaluate_model:
    runs-on: ubuntu-latest
    needs: build_docker_image_and_push  # This job will run only if previous job is successful
    steps:
      - name: Checkout docker repository
        uses: actions/checkout@v2

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: https://index.docker.io/v1/  # Dockerhub registry
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image from above repository
        run: docker pull padamsingh2024/da-201o:both_fail


      - name: Evaluate model in docker container
        run: |
          ModelScore=$(docker run -p 8080:80 --name padamsingh2024/da-201o:both_fail)
          echo "Score:"
          echo "$ModelScore"
          if [[ `echo "$ModelScore 0.50" | awk '{print ($1 < $2)}'` == 1 ]]; then echo "Insufficient Accuracy" && exit 1; fi
